# Generated by Django 2.0.2 on 2019-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('appliedfor', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('contact1', models.IntegerField(default=0)),
                ('contact2', models.IntegerField(default=0)),
                ('district', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('apppliedprogram', models.CharField(max_length=200)),
                ('durationofprogram', models.CharField(max_length=100)),
                ('durstionofmonth', models.CharField(max_length=100)),
            ],
        ),
    ]
