# Generated by Django 2.0.2 on 2019-01-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulearn', '0002_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.CharField(max_length=200),
        ),
    ]
