# Generated by Django 2.0.2 on 2019-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulearn', '0003_auto_20190121_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='contact1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact2',
            field=models.BigIntegerField(default=0),
        ),
    ]
