# Generated by Django 2.0.2 on 2019-01-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulearn', '0004_auto_20190121_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(),
        ),
    ]
