# Generated by Django 2.0.2 on 2019-01-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulearn', '0005_auto_20190121_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobileno', models.BigIntegerField(default=0)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
