# Generated by Django 2.1.2 on 2019-02-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edulearn', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted', models.IntegerField(default=0)),
            ],
        ),
    ]
